spring:
  application:
    name: orderService

  datasource:
    url: jdbc:mysql://localhost:3306/lcwd
    username: root
    password: Restinpeace11.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 9091